name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 17.x
    
      #- run: npm install --frozen-lockfile
      - run:  npm i  
     # - run: npm run lint && npm run build
      - run: npm run build
